export const RoutesName = {
  SPLASH: 'Splash',
  GET_STARTED: 'GetStarted',
  LOGIN: 'Login',

  HOME: 'Home',
  HOME_TAB: 'Home Tab',
  CONFIRMATION: 'confirm',
  CATEGORIES_STACK: 'categories stack',
  CATEGORIES: 'Categories',
  CATEGORIES_DETAILS: 'Categories Detials',
  HISTORY: 'History',
  ACCOUNTS: 'accounts',
  ACCOUNTS_STACK: 'accounts stack',
  SUGGESTED_PRODUCTS: 'suggested',
  PRIVACY_POLiCY: 'privacy policy',
  ADD_SUGESTED: 'add sugested',
  TRANSACTION_HISTORY: 'transaction history',
  REVERT_ORDER: 'revert order',
  CHECKOUT: 'checkout',
};
